[package]
name = "gemview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gmi = "~0.2"
once_cell = "1"
textwrap = "~0.14"
url = "~2.2"
webbrowser = "~0.5"

[dependencies.gtk]
version = "~0.4"
package = "gtk4"
