name: CI

on:
  push:
    branches: [ "odin" ]
  pull_request:
    branches: [ "odin" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: InstallDeps
      run: sudo apt-get install libssl-dev libgtk-4-dev
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
